version: "3.7"
services:
  flask:
    build: ./app
    container_name: flask
    restart: always
    environment:
      - APP_NAME=RetoTecnicoX
      - USER=root
      - PASSWORD=root
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8003:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro